# wrangler.toml
name = "gemini-code-api"
main = "src/index.ts"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "gemini-code"
database_id = "761cb8da-9ccf-44ee-b5a1-880678b5d6c7"