name = "gemini-code-api"
main = "src/main.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 绑定到 Cloudflare D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "gemini-code"
database_id = "d70af52a-dc4c-4826-9fdf-fa43dba1a261"

# 绑定到 Cloudflare KV 存储
[[kv_namespaces]]
binding = "KV"
id = "a6fd337e794548529e3d2cde1782a671"

[build]
command = "npm run build"

[observability.logs]
enabled = true