name = "gemini-code-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 调试模式配置

[[d1_databases]]
binding = "DB"
database_name = "gemini-code"
database_id = "71b39975-72e6-4d64-89d2-0363f3e7d161"

[build]
command = "npm run build"

[observability.logs]
enabled = true